#:schema node_modules/wrangler/config-schema.json
name = "file-link-bot"
main = "src/index.js"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "files_data", id = "fill_id_here" },
]